/**
 * Centralized Type Exports
 *
 * Re-export all types from a single entry point for convenient imports.
 */

// Database types
export type {
  Profile,
  Post,
  PostDraft,
  Comment,
  Clap,
  Bookmark,
  ReadingList,
  Highlight,
  Series,
  SeriesPost,
  Publication,
  PublicationMember,
  Category,
  Tag,
  TagFollower,
  PostVersion,
  ContentReport,
  PostView,
  MediaAsset,
  Reputation,
  Badge,
  UserBadge,
  AnalyticsEvent,
  CollaborationDocument,
} from './database';

// Analytics types
export type {
  AnalyticsPeriod,
  MetricValue,
  DashboardStats,
  TimeSeriesDataPoint,
  TimeSeriesChartData,
  PostPerformance,
  UserEngagement,
  CategoryPerformance,
  TagPerformance,
  TrafficSource,
  GeographicData,
  DeviceData,
  ReadingBehavior,
  CohortData,
  FunnelStep,
  ABTestVariant,
  ExportFormat,
  AnalyticsFilter,
  RealtimeEvent,
  AnalyticsQueryResult,
} from './analytics';

// Admin types
export type {
  AdminPermission,
  AdminRole,
  UserManagementRow,
  UserAction,
  PostManagementRow,
  PostAction,
  CommentManagementRow,
  CommentAction,
  ModerationQueueItem,
  ModerationAction,
  ModerationDecision,
  PublicationManagementRow,
  PublicationAction,
  SettingCategory,
  SettingValue,
  SystemSetting,
  DatabaseTableInfo,
  DatabaseColumnInfo,
  DatabaseIndexInfo,
  DatabaseForeignKeyInfo,
  DatabaseQueryResult,
  CategoryTagRow,
  AuditLogEntry,
  AdminDashboardOverview,
  SystemHealthMetrics,
  BatchOperationResult,
} from './admin';

// Component types
export type {
  BaseComponentProperties,
  FormFieldChangeEvent,
  FormSubmitEvent,
  MouseClickEvent,
  KeyboardEvent,
  DragEvent,
  FileInputChangeEvent,
  ToastType,
  Toast,
  ModalProperties,
  DialogAction,
  TableColumn,
  TableSortState,
  PaginationState,
  FilterState,
  SelectOption,
  TabItem,
  BreadcrumbItem,
  MenuItem,
  ChartDataPoint,
  LoadingState,
  AsyncDataState,
  FormValidationError,
  FormState,
  DropdownPosition,
  ColorScheme,
  SizeVariant,
  ButtonVariant,
  FileUploadStatus,
  InfiniteScrollState,
  VirtualizedListProperties,
  ErrorBoundaryState,
  KeyboardShortcut,
} from './components';

// Editor types
export type {
  EditorContentFormat,
  Editor,
  EditorContent,
  TextAlign,
  HeadingLevel,
  EditorToolbarButton,
  EditorToolbarGroup,
  ImageUploadResult,
  VideoEmbedData,
  CodeBlockLanguage,
  LinkAttributes,
  TableCellAttributes,
  CollaborationUser,
  CollaborationAwareness,
  MentionSuggestion,
  EmojiSuggestion,
  SlashCommandSuggestion,
  EditorStatistics,
  AutoSaveState,
  VersionHistoryEntry,
  AIWritingSuggestion,
  PexelsImage,
  MediaLibraryItem,
  EditorTheme,
  EditorMode,
  TableOfContentsItem,
  CommentThread,
} from './editor';
