name: PR Preview Deployment

on:
  pull_request:
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  NODE_VERSION: '20'

jobs:
  # Deploy preview for pull requests
  deploy-preview:
    name: Deploy PR Preview
    runs-on: ubuntu-latest
    timeout-minutes: 15
    if: github.event_name == 'pull_request'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --prefer-offline --no-audit

      - name: Build application
        run: npm run build
        env:
          NODE_ENV: production
          VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
          VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}

      - name: Deploy to Vercel Preview
        id: deploy
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          github-comment: true
          working-directory: ./

      - name: Comment preview URL
        uses: actions/github-script@v7
        with:
          script: |
            const previewUrl = '${{ steps.deploy.outputs.preview-url }}';
            const comment = `## ðŸš€ Preview Deployment Ready!

            Your preview deployment is ready for review.

            **Preview URL:** ${previewUrl}

            ### Quick Links
            - ðŸ” [View Preview](${previewUrl})
            - ðŸ“Š [View Build Logs](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})

            ### What's Included
            - âœ… Latest code changes
            - âœ… Production build
            - âœ… Connected to development database

            **Note:** This preview will be automatically updated with each commit to this PR.
            `;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });

      - name: Run lighthouse on preview
        uses: treosh/lighthouse-ci-action@v10
        with:
          urls: ${{ steps.deploy.outputs.preview-url }}
          uploadArtifacts: true
        continue-on-error: true

